core/core/urls.py
from django.contrib import admin
from django.urls import path, include
# Documentation
from rest_framework.documentation import include_docs_urls
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions

schema_view = get_schema_view(
   openapi.Info(
      title="Todo List API",
      default_version='v1',
      description="This is an api for Todo List App",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="amirzadeh@live.com"),
      license=openapi.License(name="MIT License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('todo/', include('todo.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-docs/', include_docs_urls(title='api sample')),
    path("swagger/output.json/", schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path("swagger/", schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path("redoc/", schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

core/todo/api/v1/urls.py
from rest_framework.urls import path
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'api-v1'

router = DefaultRouter()
router.register('task', views.TodoModelViewset, basename='task')

urlpatterns = router.urls

core/todo/urls.py
from django.urls import path, include
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.TodoListView.as_view(), name='todo-list'),
    path('create/', views.TodoCreateView.as_view(), name='todo-create'),
    path('<int:pk>/complete/', views.TodoCompleteView.as_view(), name='todo-complete'),
    path('<int:pk>/update/', views.TodoUpdateView.as_view(), name='todo-update'),
    path('<int:pk>/delete/', views.TodoDeleteView.as_view(), name='todo-delete'),\
    path('api/v1/', include('todo.api.v1.urls')),
]

core/todo/models.py
from django.db import models
from accounts.models import Profile

# Create your models here.
class Todo(models.Model):
    "A class for todo"
    user = models.ForeignKey('accounts.Profile', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    complete = models.BooleanField(default=False)
    due_time = models.DateTimeField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

core/todo/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):
    "A class for todo form"
    class Meta:
        model = Todo
        fields = ['title', 'due_time']

core/todo/api/v1/views.py
from rest_framework import viewsets
from rest_framework.viewsets import ModelViewSet
from .permissions import IsOwner
from .serializers import TodoSerializer
from todo.models import Todo
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter

class TodoModelViewset(viewsets.ModelViewSet):
    "A class for getting list and detail of Todo tasks"
    permission_classes = [IsOwner]
    serializer_class = TodoSerializer
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ['complete']
    search_fields = ['title']
    ordering_fields = ['complete']
    
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Todo.objects.none()
        return Todo.objects.filter(user=self.request.user.profile)

core/todo/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, CreateView, View, UpdateView, DeleteView
from .models import Todo
from .forms import TodoForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import JsonResponse
import json

# Create your views here.
class TodoListView(LoginRequiredMixin, ListView):
    "A class for todo list"
    model = Todo
    context_object_name = 'tasks'
    template_name = 'todo/todo_list.html'
    
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user.profile)
    
    
class TodoCreateView(LoginRequiredMixin, CreateView):
    "A class to create todo"
    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('todo:todo-list')
    
    def form_valid(self, form):
        form.instance.user = self.request.user.profile
        return super(TodoCreateView, self).form_valid(form)


class TodoCompleteView(LoginRequiredMixin, View):
    "A class to complete todo"
    def post(self, request, *args, **kwargs):
        task = get_object_or_404(Todo, id=kwargs.get('pk'))
        try:
            data = json.loads(request.body)
            task.complete = data.get("complete", False)
            task.save()
            return JsonResponse({"success": True, "completed": task.complete})
        except json.JSONDecodeError:
            return JsonResponse({"success": False}, status=400)
    


class TodoUpdateView(LoginRequiredMixin, UpdateView):
    "A class to update todo"
    model = Todo
    form_class = TodoForm
    template_name = 'todo/todo_update.html'
    success_url = reverse_lazy('todo:todo-list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = self.get_object()
        return context
        

class TodoDeleteView(LoginRequiredMixin, DeleteView):
    "A class to delete todo"
    model = Todo
    context_object_name = 'tasks'
    success_url = reverse_lazy('todo:todo-list')
    
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)
    
    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user.profile)

core/templates/todo/todo_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="d-flex flex-column flex-md-row p-3 align-items-center justify-content-center">
    <h2>Todo List</h2>
  </div>

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
    <a href="{% url 'blog:post-copy' pk=task.id %}">
        <h5>Delete</h5>
    </a>
</form>

{% endblock %}

core/templates/todo/todo_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="d-flex flex-column flex-md-row p-3 align-items-center justify-content-center">
  <h2>Todo List</h2>
</div>

<div class="d-flex flex-column flex-md-row p-6 gap-4 py-md-5 align-items-center justify-content-center">
  <div class="list-group">
    <form method="post" action="{% url 'todo:todo-create' %}">
      {% csrf_token %}
      <label class="list-group-item d-flex gap-3 bg-body-tertiary">
        <span class="pt-1 form-checked-content">
          <input name="title" type="text" class="form-control" id="floatingInput" placeholder="Add new task ...">
        </span>
        <input name="due_time" type="datetime-local" class="btn btn-secondary rounded-pill px-1" value="due_time"></input>
        <button class="btn btn-success rounded-pill px-3" type="submit">Add</button>
      </label>
    </form>
    {% for task in tasks %}
    <label class="list-group-item d-flex gap-3">
      <input class="form-check-input flex-shrink-0" type="checkbox" value="" checked style="font-size: 1.375em;">
      <span class="pt-1 form-checked-content">
        <strong>{{task.title}}</strong>
        <small class="d-block text-body-secondary">
          <svg class="bi me-1" width="1em" height="1em"><use xlink:href="#calendar-event"/></svg>
          {{task.due_time}}
        </small>
      </span>
    </label>
    {% endfor %}
  </div>
</div>

{% endblock %}

core/templates/todo/todo_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="d-flex flex-column flex-md-row p-3 align-items-center justify-content-center">
  <h2>Todo List</h2>
</div>

<div class="d-flex flex-column flex-md-row p-6 gap-4 py-md-5 align-items-center justify-content-center">
  <div class="list-group">
    <form method="post" action="{% url 'todo:todo-create' %}">
      {% csrf_token %}
      <label class="list-group-item d-flex gap-3 bg-body-tertiary">
        <span class="pt-1 form-checked-content">
          <input name="title" type="text" class="form-control px-2" id="floatingInput" placeholder="Add new task ...">
        </span>
        <input name="due_time" type="datetime-local" class="btn btn-secondary rounded-pill px-1" value="due_time">
        <button class="btn btn-success rounded-pill px-3" type="submit">Add</button>
      </label>
    </form>

    {% for task in tasks %}
    <label class="list-group-item d-flex align-items-center justify-content-between">
      <div class="d-flex align-items-center gap-3">
        <input type="checkbox" class="form-check-input task-checkbox"
          data-url="{% url 'todo:todo-complete' pk=task.id %}" {% if task.complete %} checked {% endif %} style="font-size: 1.375em;">
        <input type="text" class="form-control task-title" value="{{ task.title }}" readonly>
        <small class="text-body-secondary">
          <svg class="bi me-1" width="1em" height="1em">
            <use xlink:href="#calendar-event" />
          </svg>
          {{ task.due_time }}
        </small>
      </div>

      <div class="d-flex align-items-center gap-2 ms-auto">
        <form method="post" action="{% url 'todo:todo-update' pk=task.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
              <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
            </svg> Edit
          </button>
        </form>

        <form method="post" action="{% url 'todo:todo-delete' pk=task.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-outline-danger">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash"
              viewBox="0 0 16 16">
              <path
                d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z">
              </path>
              <path
                d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z">
              </path>
            </svg>
          </button>
        </form>
      </div>
    </label>
    {% endfor %}
  </div>
</div>

<script>
  document.querySelectorAll(".task-checkbox").forEach(checkbox => {
    checkbox.addEventListener("change", function () {
      const url = this.getAttribute("data-url");
      const isChecked = this.checked;

      fetch(url, {
        method: "POST",
        headers: {
          "X-CSRFToken": getCookie("csrftoken"),
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ complete: isChecked })
      })
        .then(response => response.json())
        .then(data => {
          if (!data.success) {
            alert("Error updating task");
            this.checked = !this.checked;
          }
        })
        .catch(error => console.error("Error:", error));
    });
  });

  function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      const cookies = document.cookie.split(';');
      for (let i = 0; i < cookies.length; i++) {
        const cookie = cookies[i].trim();
        if (cookie.startsWith(name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
</script>

{% endblock %}

core/templates/todo/todo_update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="d-flex flex-column flex-md-row p-3 align-items-center justify-content-center">
  <h2>Todo List</h2>
</div>

<div class="d-flex flex-column flex-md-row p-6 gap-4 py-md-5 align-items-center justify-content-center">
  <div class="list-group">
    <form method="post" action="{% url 'todo:todo-update' pk=task.id %}">
      {% csrf_token %}
      <label class="list-group-item d-flex gap-1 bg-body-tertiary">
        <span class="pt-1 form-checked-content">
          <input name="title" type="text" class="form-control" id="floatingInput" value="{{task.title}}">
        </span>
        <input name="due_time" type="datetime-local" class="btn btn-secondary rounded-pill px-1"
          value="{{ task.due_time|date:'Y-m-d\TH:i' }}">
        <button class="btn btn-success rounded-pill px-3" type="submit">Update</button>
      </label>
    </form>
  </div>
</div>

{% endblock %}